export default {
  staking: '/staking',
  myStaking: '/myStaking',
  stakingDetail: '/validators/:validatorAddress',
  gov: '/gov',
  proposalDetail: '/proposal/:proposalId',
  bridge: '/bridge/:tab',
  btcbridge: '/bridge/btc',
  faucet: '/faucet',
  explorer: '/explorer',
  pool: '/pool',
  poolDetail: '/pool/:contract_addr/:liquidity_token/:type?',
  swap: '/swap',
  asset: '/asset',
  summon: '/summon',
  summonDetail: '/summon/:summonId',
};
